DROP TABLE IF EXISTS T_EXPO_EXP;
DROP TABLE IF EXISTS T_OEUVRE_OVR;
DROP TABLE IF EXISTS T_AUTEUR_AUT;
DROP TABLE IF EXISTS T_VISITEUR_VIS;
DROP TABLE IF EXISTS T_USER_USR;
DROP TABLE IF EXISTS T_NEWS_NEW;